<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class BookSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $books = [
            [
                'id' => "001",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 1,
                'title' => 'Bahasa Indonesia X',
                'publisher' => 'Yrama Widya',
                'author' => 'Yadi Mulyadi',
                'type' => 'offline',
                'year' => null,
                'stock' => 15,
                'cover' => null,
            ],
            [
                'id' => "002",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 1,
                'title' => 'Bahasa Indonesia XI',
                'publisher' => 'Yrama Widya',
                'author' => 'Yadi Mulyadi',
                'type' => 'offline',
                'year' => null,
                'stock' => 18,
                'cover' => null,
            ],
            [
                'id' => "003",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 1,
                'title' => 'Bahasa Indonesia XII',
                'publisher' => 'Yrama Widya',
                'author' => 'Yadi Mulyadi',
                'type' => 'offline',
                'year' => null,
                'stock' => 14,
                'cover' => null,
            ],
            [
                'id' => "004",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 1,
                'title' => 'Matematika X',
                'publisher' => 'Yrama Widya',
                'author' => 'Suah Sembiring',
                'type' => 'offline',
                'year' => null,
                'stock' => 17,
                'cover' => null,
            ],
            [
                'id' => "005",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 1,
                'title' => 'Matematika XI',
                'publisher' => 'Yrama Widya',
                'author' => 'Suah Sembiring',
                'type' => 'offline',
                'year' => null,
                'stock' => 20,
                'cover' => null,
            ],
            [
                'id' => "006",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 1,
                'title' => 'Matematika XII',
                'publisher' => 'Yrama Widya',
                'author' => 'Suah Sembiring',
                'type' => 'offline',
                'year' => null,
                'stock' => 14,
                'cover' => null,
            ],
            [
                'id' => "007",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 1,
                'title' => 'Fisika X',
                'publisher' => 'Yrama Widya',
                'author' => 'Marthen Kanginan',
                'type' => 'offline',
                'year' => null,
                'stock' => 18,
                'cover' => null,
            ],
            [
                'id' => "008",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 1,
                'title' => 'Fisika XI',
                'publisher' => 'Yrama Widya',
                'author' => 'Marthen Kanginan',
                'type' => 'offline',
                'year' => null,
                'stock' => 18,
                'cover' => null,
            ],
            [
                'id' => "009",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 1,
                'title' => 'Fisika XII',
                'publisher' => 'Yrama Widya',
                'author' => 'Marthen Kanginan',
                'type' => 'offline',
                'year' => null,
                'stock' => 16,
                'cover' => null,
            ],
            [
                'id' => "010",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 1,
                'title' => 'Kimia X',
                'publisher' => 'Erlangga',
                'author' => 'Dra. Nefoyati, MM.',
                'type' => 'offline',
                'year' => null,
                'stock' => 15,
                'cover' => null,
            ],
            [
                'id' => "011",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 1,
                'title' => 'Kimia XI',
                'publisher' => 'Erlangga',
                'author' => 'Dra. Nefoyati, MM.',
                'type' => 'offline',
                'year' => null,
                'stock' => 14,
                'cover' => null,
            ],
            [
                'id' => "012",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 1,
                'title' => 'Kimia XII',
                'publisher' => 'Erlangga',
                'author' => 'Dra. Nefoyati, MM.',
                'type' => 'offline',
                'year' => null,
                'stock' => 13,
                'cover' => null,
            ],
            [
                'id' => "055",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 2,
                'title' => 'Ilmu Gizi X',
                'publisher' => 'AndiPublisher',
                'author' => 'Nursari Handayani, M.Pd.',
                'type' => 'offline',
                'year' => null,
                'stock' => 10,
                'cover' => null,
            ],
            [
                'id' => "056",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 2,
                'title' => 'Ilmu Gizi XI',
                'publisher' => 'AndiPublisher',
                'author' => 'Nursari Handayani, M.Pd.',
                'type' => 'offline',
                'year' => null,
                'stock' => 10,
                'cover' => null,
            ],
            [
                'id' => "057",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 2,
                'title' => 'Ilmu Gizi XII',
                'publisher' => 'AndiPublisher',
                'author' => 'Nursari Handayani, M.Pd.',
                'type' => 'offline',
                'year' => null,
                'stock' => 10,
                'cover' => null,
            ],
            [
                'id' => "058",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 2,
                'title' => 'Konsep Dasar Keperawatan X',
                'publisher' => 'AndiPublisher',
                'author' => 'Yeni Lestari',
                'type' => 'offline',
                'year' => null,
                'stock' => 9,
                'cover' => null,
            ],
            [
                'id' => "059",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 2,
                'title' => 'Konsep Dasar Keperawatan XI',
                'publisher' => 'AndiPublisher',
                'author' => 'Yeni Lestari',
                'type' => 'offline',
                'year' => null,
                'stock' => 9,
                'cover' => null,
            ],
            [
                'id' => "060",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 2,
                'title' => 'Konsep Dasar Keperawatan XII',
                'publisher' => 'AndiPublisher',
                'author' => 'Yeni Lestari',
                'type' => 'offline',
                'year' => null,
                'stock' => 9,
                'cover' => null,
            ],
            [
                'id' => "061",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 2,
                'title' => 'Praktek Pelayanan Farmasi X',
                'publisher' => 'APMFI',
                'author' => 'apt. Andri Priyoherianto, S.Farm., M.Si',
                'type' => 'offline',
                'year' => null,
                'stock' => 12,
                'cover' => null,
            ],
            [
                'id' => "062",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 2,
                'title' => 'Praktek Pelayanan Farmasi XI',
                'publisher' => 'APMFI',
                'author' => 'apt. Andri Priyoherianto, S.Farm., M.Si',
                'type' => 'offline',
                'year' => null,
                'stock' => 12,
                'cover' => null,
            ],
            [
                'id' => "063",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 2,
                'title' => 'Praktek Pelayanan Farmasi XII',
                'publisher' => 'APMFI',
                'author' => 'apt. Andri Priyoherianto, S.Farm., M.Si',
                'type' => 'offline',
                'year' => null,
                'stock' => 12,
                'cover' => null,
            ],
            [
                'id' => "084",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 3,
                'title' => 'Informatika Kesehatan',
                'publisher' => 'Erlangga',
                'author' => 'Andi Novianto',
                'type' => 'offline',
                'year' => null,
                'stock' => 12,
                'cover' => null,
            ],
            [
                'id' => "085",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 3,
                'title' => 'Kewirausahaan',
                'publisher' => 'Rajawali Pers',
                'author' => 'Dr. Kasmir, S.E, M.M.',
                'type' => 'offline',
                'year' => null,
                'stock' => 12,
                'cover' => null,
            ],
            [
                'id' => "086",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 3,
                'title' => 'Desain Media Interaktif',
                'publisher' => 'Erlangga',
                'author' => 'Drs.Siwi Widi Asmoro',
                'type' => 'offline',
                'year' => null,
                'stock' => 12,
                'cover' => null,
            ],
        ];

        foreach ($books as $book) {
            \App\Models\Book::create($book);
        }
    }
}
