<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class BookSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $books = [
            [
                'id' => "001",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 1,
                'title' => 'Bahasa Indonesia X',
                'publisher' => 'Yrama Widya',
                'author' => 'Yadi Mulyadi',
                'type' => 'offline',
                'year' => null,
                'stock' => 15,
                'cover' => null,
            ],
            [
                'id' => "002",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 1,
                'title' => 'Bahasa Indonesia XI',
                'publisher' => 'Yrama Widya',
                'author' => 'Yadi Mulyadi',
                'type' => 'offline',
                'year' => null,
                'stock' => 18,
                'cover' => null,
            ],
            [
                'id' => "003",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 1,
                'title' => 'Bahasa Indonesia XII',
                'publisher' => 'Yrama Widya',
                'author' => 'Yadi Mulyadi',
                'type' => 'offline',
                'year' => null,
                'stock' => 14,
                'cover' => null,
            ],
            [
                'id' => "004",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 1,
                'title' => 'Matematika X',
                'publisher' => 'Yrama Widya',
                'author' => 'Suah Sembiring',
                'type' => 'offline',
                'year' => null,
                'stock' => 17,
                'cover' => null,
            ],
            [
                'id' => "005",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 1,
                'title' => 'Matematika XI',
                'publisher' => 'Yrama Widya',
                'author' => 'Suah Sembiring',
                'type' => 'offline',
                'year' => null,
                'stock' => 20,
                'cover' => null,
            ],
            [
                'id' => "006",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 1,
                'title' => 'Matematika XII',
                'publisher' => 'Yrama Widya',
                'author' => 'Suah Sembiring',
                'type' => 'offline',
                'year' => null,
                'stock' => 14,
                'cover' => null,
            ],
            [
                'id' => "007",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 1,
                'title' => 'Fisika X',
                'publisher' => 'Yrama Widya',
                'author' => 'Marthen Kanginan',
                'type' => 'offline',
                'year' => null,
                'stock' => 18,
                'cover' => null,
            ],
            [
                'id' => "008",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 1,
                'title' => 'Fisika XI',
                'publisher' => 'Yrama Widya',
                'author' => 'Marthen Kanginan',
                'type' => 'offline',
                'year' => null,
                'stock' => 18,
                'cover' => null,
            ],
            [
                'id' => "009",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 1,
                'title' => 'Fisika XII',
                'publisher' => 'Yrama Widya',
                'author' => 'Marthen Kanginan',
                'type' => 'offline',
                'year' => null,
                'stock' => 16,
                'cover' => null,
            ],
            [
                'id' => "010",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 1,
                'title' => 'Kimia X',
                'publisher' => 'Erlangga',
                'author' => 'Dra. Nefoyati, MM.',
                'type' => 'offline',
                'year' => null,
                'stock' => 15,
                'cover' => null,
            ],
            [
                'id' => "011",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 1,
                'title' => 'Kimia XI',
                'publisher' => 'Erlangga',
                'author' => 'Dra. Nefoyati, MM.',
                'type' => 'offline',
                'year' => null,
                'stock' => 14,
                'cover' => null,
            ],
            [
                'id' => "012",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 1,
                'title' => 'Kimia XII',
                'publisher' => 'Erlangga',
                'author' => 'Dra. Nefoyati, MM.',
                'type' => 'offline',
                'year' => null,
                'stock' => 13,
                'cover' => null,
            ],
            [
                'id' => "013",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 1,
                'title' => 'Dasar Pemrograman X',
                'publisher' => 'Erlangga',
                'author' => 'Andi Novianto',
                'type' => 'offline',
                'year' => null,
                'stock' => 10,
                'cover' => null,
            ],
            [
                'id' => "014",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 1,
                'title' => 'Dasar Pemrograman XI',
                'publisher' => 'Erlangga',
                'author' => 'Andi Novianto',
                'type' => 'offline',
                'year' => null,
                'stock' => 10,
                'cover' => null,
            ],
            [
                'id' => "015",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 1,
                'title' => 'Dasar Pemrograman XII',
                'publisher' => 'Erlangga',
                'author' => 'Andi Novianto',
                'type' => 'offline',
                'year' => null,
                'stock' => 10,
                'cover' => null,
            ],
            [
                'id' => "016",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 1,
                'title' => 'Sejarah Indonesia X',
                'publisher' => 'Erlangga',
                'author' => 'Ratna Hapsari',
                'type' => 'offline',
                'year' => null,
                'stock' => 12,
                'cover' => null,
            ],
            [
                'id' => "017",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 1,
                'title' => 'Sejarah Indonesia XI',
                'publisher' => 'Erlangga',
                'author' => 'Ratna Hapsari',
                'type' => 'offline',
                'year' => null,
                'stock' => 13,
                'cover' => null,
            ],
            [
                'id' => "018",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 1,
                'title' => 'Sejarah Indonesia XII',
                'publisher' => 'Erlangga',
                'author' => 'Ratna Hapsari',
                'type' => 'offline',
                'year' => null,
                'stock' => 13,
                'cover' => null,
            ],
            [
                'id' => "019",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 1,
                'title' => 'Pemrograman Dasar',
                'publisher' => 'Yudi Tira',
                'author' => 'Heryanto',
                'type' => 'offline',
                'year' => null,
                'stock' => 9,
                'cover' => null,
            ],
            [
                'id' => "020",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 1,
                'title' => 'Informatika Teknologi X',
                'publisher' => 'Erlangga',
                'author' => 'Andi Novianto',
                'type' => 'offline',
                'year' => null,
                'stock' => 9,
                'cover' => null,
            ],
            [
                'id' => "021",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 1,
                'title' => 'Informatika',
                'publisher' => 'Erlangga',
                'author' => 'Andi Novianto',
                'type' => 'offline',
                'year' => null,
                'stock' => 9,
                'cover' => null,
            ],
            [
                'id' => "022",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 1,
                'title' => 'Pendidikan Pancasila X',
                'publisher' => 'Yrama Widya',
                'author' => 'M. Taupan & Ine Ariyani S.',
                'type' => 'offline',
                'year' => null,
                'stock' => 11,
                'cover' => null,
            ],
            [
                'id' => "023",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 1,
                'title' => 'Pendidikan Pancasila XI',
                'publisher' => 'Yrama Widya',
                'author' => 'M. Taupan & Ine Ariyani S.',
                'type' => 'offline',
                'year' => null,
                'stock' => 17,
                'cover' => null,
            ],
            [
                'id' => "024",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 1,
                'title' => 'Pendidikan Pancasila XII',
                'publisher' => 'Yrama Widya',
                'author' => 'M. Taupan & Ine Ariyani S.',
                'type' => 'offline',
                'year' => null,
                'stock' => 17,
                'cover' => null,
            ],
            [
                'id' => "025",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 1,
                'title' => 'Bahasa Inggris X',
                'publisher' => 'Yrama Widya',
                'author' => 'Otong Setiawan Djuharie',
                'type' => 'offline',
                'year' => null,
                'stock' => 10,
                'cover' => null,
            ],
            [
                'id' => "026",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 1,
                'title' => 'Bahasa Inggris XI',
                'publisher' => 'Yrama Widya',
                'author' => 'Otong Setiawan Djuharie',
                'type' => 'offline',
                'year' => null,
                'stock' => 19,
                'cover' => null,
            ],
            [
                'id' => "027",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 1,
                'title' => 'Bahasa Inggris XII',
                'publisher' => 'Yrama Widya',
                'author' => 'Otong Setiawan Djuharie',
                'type' => 'offline',
                'year' => null,
                'stock' => 20,
                'cover' => null,
            ],
            [
                'id' => "028",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 1,
                'title' => 'Penjas Orkes X',
                'publisher' => 'Yrama Widya',
                'author' => 'Khairul Hadziq',
                'type' => 'offline',
                'year' => null,
                'stock' => 18,
                'cover' => null,
            ],
            [
                'id' => "029",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 1,
                'title' => 'Penjas Orkes XI',
                'publisher' => 'Yrama Widya',
                'author' => 'Khairul Hadziq',
                'type' => 'offline',
                'year' => null,
                'stock' => 18,
                'cover' => null,
            ],
            [
                'id' => "030",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 1,
                'title' => 'Penjas Orkes XII',
                'publisher' => 'Yrama Widya',
                'author' => 'Khairul Hadziq',
                'type' => 'offline',
                'year' => null,
                'stock' => 18,
                'cover' => null,
            ],
            [
                'id' => "031",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 1,
                'title' => 'Komputer Akuntansi X',
                'publisher' => 'AndiPublisher',
                'author' => 'Agus Mulyono, S.E.',
                'type' => 'offline',
                'year' => null,
                'stock' => 11,
                'cover' => null,
            ],
            [
                'id' => "032",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 1,
                'title' => 'Komputer Akuntansi XI',
                'publisher' => 'AndiPublisher',
                'author' => 'Agus Mulyono, S.E.',
                'type' => 'offline',
                'year' => null,
                'stock' => 10,
                'cover' => null,
            ],
            [
                'id' => "033",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 1,
                'title' => 'Komputer Akuntansi XII',
                'publisher' => 'AndiPublisher',
                'author' => 'Agus Mulyono, S.E.',
                'type' => 'offline',
                'year' => null,
                'stock' => 10,
                'cover' => null,
            ],
            [
                'id' => "034",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 1,
                'title' => 'Teknologi Jaringan Berbasis Luas X',
                'publisher' => 'AndiPublisher',
                'author' => 'Patwiyanto, S.Kom.',
                'type' => 'offline',
                'year' => null,
                'stock' => 11,
                'cover' => null,
            ],
            [
                'id' => "035",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 1,
                'title' => 'Teknologi Jaringan Berbasis Luas XI',
                'publisher' => 'AndiPublisher',
                'author' => 'Patwiyanto, S.Kom.',
                'type' => 'offline',
                'year' => null,
                'stock' => 11,
                'cover' => null,
            ],
            [
                'id' => "036",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 1,
                'title' => 'Teknologi Jaringan Berbasis Luas XII',
                'publisher' => 'AndiPublisher',
                'author' => 'Patwiyanto, S.Kom.',
                'type' => 'offline',
                'year' => null,
                'stock' => 11,
                'cover' => null,
            ],
            [
                'id' => "037",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 1,
                'title' => 'Teknologi Layanan Jaringan X',
                'publisher' => 'AndiPublisher',
                'author' => 'Sri Wahyuni S.Kom.',
                'type' => 'offline',
                'year' => null,
                'stock' => 9,
                'cover' => null,
            ],
            [
                'id' => "038",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 1,
                'title' => 'Teknologi Layanan Jaringan XI',
                'publisher' => 'AndiPublisher',
                'author' => 'Sri Wahyuni S.Kom.',
                'type' => 'offline',
                'year' => null,
                'stock' => 9,
                'cover' => null,
            ],
            [
                'id' => "039",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 1,
                'title' => 'Teknologi Layanan Jaringan XII',
                'publisher' => 'AndiPublisher',
                'author' => 'Sri Wahyuni S.Kom.',
                'type' => 'offline',
                'year' => null,
                'stock' => 9,
                'cover' => null,
            ],
            [
                'id' => "040",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 1,
                'title' => 'Adminstrasi Infrastruktur Jaringan X',
                'publisher' => 'Gino Guruputra',
                'author' => 'Waluyo',
                'type' => 'offline',
                'year' => null,
                'stock' => 8,
                'cover' => null,
            ],
            [
                'id' => "041",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 1,
                'title' => 'Adminstrasi Infrastruktur Jaringan XI',
                'publisher' => 'Gino Guruputra',
                'author' => 'Waluyo',
                'type' => 'offline',
                'year' => null,
                'stock' => 8,
                'cover' => null,
            ],
            [
                'id' => "042",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 1,
                'title' => 'Adminstrasi Infrastruktur Jaringan XII',
                'publisher' => 'Gino Guruputra',
                'author' => 'Waluyo',
                'type' => 'offline',
                'year' => null,
                'stock' => 8,
                'cover' => null,
            ],
            [
                'id' => "043",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 1,
                'title' => 'Administrasi Sistem Jaringan X',
                'publisher' => 'Cipta Media Edukasi',
                'author' => 'Nikmah Daulae',
                'type' => 'offline',
                'year' => null,
                'stock' => 10,
                'cover' => null,
            ],
            [
                'id' => "044",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 1,
                'title' => 'Administrasi Sistem Jaringan XI',
                'publisher' => 'Cipta Media Edukasi',
                'author' => 'Nikmah Daulae',
                'type' => 'offline',
                'year' => null,
                'stock' => 9,
                'cover' => null,
            ],
            [
                'id' => "045",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 1,
                'title' => 'Administrasi Sistem Jaringan XII',
                'publisher' => 'Cipta Media Edukasi',
                'author' => 'Nikmah Daulae',
                'type' => 'offline',
                'year' => null,
                'stock' => 10,
                'cover' => null,
            ],
            [
                'id' => "046",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 1,
                'title' => 'Administrasi Sistem Jaringan X',
                'publisher' => 'AndiPublisher',
                'author' => 'Patwiyanto, S.Kom.',
                'type' => 'offline',
                'year' => null,
                'stock' => 14,
                'cover' => null,
            ],
            [
                'id' => "047",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 1,
                'title' => 'Administrasi Sistem Jaringan XI',
                'publisher' => 'AndiPublisher',
                'author' => 'Patwiyanto, S.Kom.',
                'type' => 'offline',
                'year' => null,
                'stock' => 14,
                'cover' => null,
            ],
            [
                'id' => "048",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 1,
                'title' => 'Administrasi Sistem Jaringan XII',
                'publisher' => 'AndiPublisher',
                'author' => 'Patwiyanto, S.Kom.',
                'type' => 'offline',
                'year' => null,
                'stock' => 14,
                'cover' => null,
            ],
            [
                'id' => "049",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 1,
                'title' => 'Sistem Komputer X',
                'publisher' => 'AndiPublisher',
                'author' => 'Sumari Agus Prasetyo, S.Kom',
                'type' => 'offline',
                'year' => null,
                'stock' => 10,
                'cover' => null,
            ],
            [
                'id' => "050",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 1,
                'title' => 'Sistem Komputer XI',
                'publisher' => 'AndiPublisher',
                'author' => 'Sumari Agus Prasetyo, S.Kom',
                'type' => 'offline',
                'year' => null,
                'stock' => 10,
                'cover' => null,
            ],
            [
                'id' => "051",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 1,
                'title' => 'Sistem Komputer XII',
                'publisher' => 'AndiPublisher',
                'author' => 'Sumari Agus Prasetyo, S.Kom',
                'type' => 'offline',
                'year' => null,
                'stock' => 10,
                'cover' => null,
            ],
            [
                'id' => "052",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 1,
                'title' => 'Dasar Desain Grafis X',
                'publisher' => 'Grafindo Media Pratama',
                'author' => 'Nichi Hana',
                'type' => 'offline',
                'year' => null,
                'stock' => 9,
                'cover' => null,
            ],
            [
                'id' => "053",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 1,
                'title' => 'Dasar Desain Grafis XI',
                'publisher' => 'Grafindo Media Pratama',
                'author' => 'Nichi Hana',
                'type' => 'offline',
                'year' => null,
                'stock' => 9,
                'cover' => null,
            ],
            [
                'id' => "054",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 1,
                'title' => 'Dasar Desain Grafis XII',
                'publisher' => 'Grafindo Media Pratama',
                'author' => 'Nichi Hana',
                'type' => 'offline',
                'year' => null,
                'stock' => 9,
                'cover' => null,
            ],
            [
                'id' => "055",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 2,
                'title' => 'Ilmu Gizi X',
                'publisher' => 'AndiPublisher',
                'author' => 'Nursari Handayani, M.Pd.',
                'type' => 'offline',
                'year' => null,
                'stock' => 10,
                'cover' => null,
            ],
            [
                'id' => "056",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 2,
                'title' => 'Ilmu Gizi XI',
                'publisher' => 'AndiPublisher',
                'author' => 'Nursari Handayani, M.Pd.',
                'type' => 'offline',
                'year' => null,
                'stock' => 10,
                'cover' => null,
            ],
            [
                'id' => "057",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 2,
                'title' => 'Ilmu Gizi XII',
                'publisher' => 'AndiPublisher',
                'author' => 'Nursari Handayani, M.Pd.',
                'type' => 'offline',
                'year' => null,
                'stock' => 10,
                'cover' => null,
            ],
            [
                'id' => "058",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 2,
                'title' => 'Konsep Dasar Keperawatan X',
                'publisher' => 'AndiPublisher',
                'author' => 'Yeni Lestari',
                'type' => 'offline',
                'year' => null,
                'stock' => 9,
                'cover' => null,
            ],
            [
                'id' => "059",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 2,
                'title' => 'Konsep Dasar Keperawatan XI',
                'publisher' => 'AndiPublisher',
                'author' => 'Yeni Lestari',
                'type' => 'offline',
                'year' => null,
                'stock' => 9,
                'cover' => null,
            ],
            [
                'id' => "060",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 2,
                'title' => 'Konsep Dasar Keperawatan XII',
                'publisher' => 'AndiPublisher',
                'author' => 'Yeni Lestari',
                'type' => 'offline',
                'year' => null,
                'stock' => 9,
                'cover' => null,
            ],
            [
                'id' => "061",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 2,
                'title' => 'Praktek Pelayanan Farmasi X',
                'publisher' => 'APMFI',
                'author' => 'apt. Andri Priyoherianto, S.Farm., M.Si',
                'type' => 'offline',
                'year' => null,
                'stock' => 12,
                'cover' => null,
            ],
            [
                'id' => "062",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 2,
                'title' => 'Praktek Pelayanan Farmasi XI',
                'publisher' => 'APMFI',
                'author' => 'apt. Andri Priyoherianto, S.Farm., M.Si',
                'type' => 'offline',
                'year' => null,
                'stock' => 12,
                'cover' => null,
            ],
            [
                'id' => "063",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 2,
                'title' => 'Praktek Pelayanan Farmasi XII',
                'publisher' => 'APMFI',
                'author' => 'apt. Andri Priyoherianto, S.Farm., M.Si',
                'type' => 'offline',
                'year' => null,
                'stock' => 12,
                'cover' => null,
            ],
            [
                'id' => "064",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 2,
                'title' => 'Anatomi dan Fisiologi X',
                'publisher' => 'AndiPublisher',
                'author' => 'yeni Lestari, S.Kep.',
                'type' => 'offline',
                'year' => null,
                'stock' => 11,
                'cover' => null,
            ],
            [
                'id' => "065",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 2,
                'title' => 'Anatomi dan Fisiologi XI',
                'publisher' => 'AndiPublisher',
                'author' => 'yeni Lestari, S.Kep.',
                'type' => 'offline',
                'year' => null,
                'stock' => 11,
                'cover' => null,
            ],
            [
                'id' => "066",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 2,
                'title' => 'Anatomi dan Fisiologi XII',
                'publisher' => 'AndiPublisher',
                'author' => 'yeni Lestari, S.Kep.',
                'type' => 'offline',
                'year' => null,
                'stock' => 11,
                'cover' => null,
            ],
            [
                'id' => "067",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 2,
                'title' => 'Komunikasi Keperawatan X',
                'publisher' => 'AndiPublisher',
                'author' => 'Dodik Aprilianto',
                'type' => 'offline',
                'year' => null,
                'stock' => 8,
                'cover' => null,
            ],
            [
                'id' => "068",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 2,
                'title' => 'Komunikasi Keperawatan XI',
                'publisher' => 'AndiPublisher',
                'author' => 'Dodik Aprilianto',
                'type' => 'offline',
                'year' => null,
                'stock' => 8,
                'cover' => null,
            ],
            [
                'id' => "069",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 2,
                'title' => 'Komunikasi Keperawatan XII',
                'publisher' => 'AndiPublisher',
                'author' => 'Dodik Aprilianto',
                'type' => 'offline',
                'year' => null,
                'stock' => 8,
                'cover' => null,
            ],
            [
                'id' => "070",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 2,
                'title' => 'Keterampilan Dasar Tindakan Keperawatan X',
                'publisher' => 'AndiPublisher',
                'author' => 'eni Lestari, S.Kep.',
                'type' => 'offline',
                'year' => null,
                'stock' => 7,
                'cover' => null,
            ],
            [
                'id' => "071",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 2,
                'title' => 'Keterampilan Dasar Tindakan Keperawatan XI',
                'publisher' => 'AndiPublisher',
                'author' => 'eni Lestari, S.Kep.',
                'type' => 'offline',
                'year' => null,
                'stock' => 7,
                'cover' => null,
            ],
            [
                'id' => "072",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 2,
                'title' => 'Keterampilan Dasar Tindakan Keperawatan XII',
                'publisher' => 'AndiPublisher',
                'author' => 'eni Lestari, S.Kep.',
                'type' => 'offline',
                'year' => null,
                'stock' => 7,
                'cover' => null,
            ],
            [
                'id' => "073",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 2,
                'title' => 'Simulasi dan Komunikasi Digitak X',
                'publisher' => 'AndiPublisher',
                'author' => 'Drs.Siwi Widi Asmoro, M.Pd.',
                'type' => 'offline',
                'year' => null,
                'stock' => 9,
                'cover' => null,
            ],
            [
                'id' => "074",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 2,
                'title' => 'Simulasi dan Komunikasi Digitak XI',
                'publisher' => 'AndiPublisher',
                'author' => 'Drs.Siwi Widi Asmoro, M.Pd.',
                'type' => 'offline',
                'year' => null,
                'stock' => 9,
                'cover' => null,
            ],
            [
                'id' => "075",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 2,
                'title' => 'Simulasi dan Komunikasi Digitak XII',
                'publisher' => 'AndiPublisher',
                'author' => 'Drs.Siwi Widi Asmoro, M.Pd.',
                'type' => 'offline',
                'year' => null,
                'stock' => 9,
                'cover' => null,
            ],
            [
                'id' => "076",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 2,
                'title' => 'Biologi X',
                'publisher' => 'Erlangga',
                'author' => 'Mieke Miarsyah',
                'type' => 'offline',
                'year' => null,
                'stock' => 10,
                'cover' => null,
            ],
            [
                'id' => "077",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 2,
                'title' => 'Biologi XI',
                'publisher' => 'Erlangga',
                'author' => 'Mieke Miarsyah',
                'type' => 'offline',
                'year' => null,
                'stock' => 10,
                'cover' => null,
            ],
            [
                'id' => "078",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 2,
                'title' => 'Biologi XII',
                'publisher' => 'Erlangga',
                'author' => 'Mieke Miarsyah',
                'type' => 'offline',
                'year' => null,
                'stock' => 10,
                'cover' => null,
            ],
            [
                'id' => "079",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 2,
                'title' => 'Ilmu Kesehatan Masyarakat X',
                'publisher' => 'AndiPublisher',
                'author' => 'I Ketut Swarjana',
                'type' => 'offline',
                'year' => null,
                'stock' => 7,
                'cover' => null,
            ],
            [
                'id' => "080",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 2,
                'title' => 'Ilmu Kesehatan Masyarakat XI',
                'publisher' => 'AndiPublisher',
                'author' => 'I Ketut Swarjana',
                'type' => 'offline',
                'year' => null,
                'stock' => 7,
                'cover' => null,
            ],
            [
                'id' => "081",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 2,
                'title' => 'Ilmu Kesehatan Masyarakat XII',
                'publisher' => 'AndiPublisher',
                'author' => 'I Ketut Swarjana',
                'type' => 'offline',
                'year' => null,
                'stock' => 7,
                'cover' => null,
            ],
            [
                'id' => "082",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 2,
                'title' => 'Kebutuhan Dasar Manusia',
                'publisher' => 'AndiPublisher',
                'author' => 'Yeni Lestari',
                'type' => 'offline',
                'year' => null,
                'stock' => 6,
                'cover' => null,
            ],
            [
                'id' => "083",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 2,
                'title' => 'Ilmu Penyakit dan Penunjang Diagnostik',
                'publisher' => 'Bumi Aksara',
                'author' => 'Sholikha Dela Aprilia',
                'type' => 'offline',
                'year' => null,
                'stock' => 8,
                'cover' => null,
            ],
            [
                'id' => "084",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 3,
                'title' => 'Informatika Kesehatan',
                'publisher' => 'Erlangga',
                'author' => 'Andi Novianto',
                'type' => 'offline',
                'year' => null,
                'stock' => 1,
                'cover' => null,
            ],
            [
                'id' => "085",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 3,
                'title' => 'Kewirausahaan',
                'publisher' => 'Rajawali Pers',
                'author' => 'Dr. Kasmir, S.E, M.M.',
                'type' => 'offline',
                'year' => null,
                'stock' => 1,
                'cover' => null,
            ],
            [
                'id' => "086",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 3,
                'title' => 'Desain Media Interaktif',
                'publisher' => 'Erlangga',
                'author' => 'Drs.Siwi Widi Asmoro',
                'type' => 'offline',
                'year' => null,
                'stock' => 1,
                'cover' => null,
            ],
            [
                'id' => "087",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 3,
                'title' => 'Produk Kreatif dan Kewirausahaan',
                'publisher' => 'Erlangga',
                'author' => 'Z. Furqon, S.T.',
                'type' => 'offline',
                'year' => null,
                'stock' => 9,
                'cover' => null,
            ],
            [
                'id' => "088",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 3,
                'title' => 'Korespondensi',
                'publisher' => '-',
                'author' => 'Drs. Joko Pramono',
                'type' => 'offline',
                'year' => null,
                'stock' => 1,
                'cover' => null,
            ],
            [
                'id' => "089",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 3,
                'title' => 'Kecerdasan Buatan',
                'publisher' => '-',
                'author' => 'T.Sutojo',
                'type' => 'offline',
                'year' => null,
                'stock' => 1,
                'cover' => null,
            ],
            [
                'id' => "090",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 3,
                'title' => 'Komputer dan Jaringan dasar',
                'publisher' => '-',
                'author' => 'Patwiyanto, S.Kom.',
                'type' => 'offline',
                'year' => null,
                'stock' => 3,
                'cover' => null,
            ],
            [
                'id' => "091",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 3,
                'title' => 'Administrasi Sistem Jaringan',
                'publisher' => 'AndiPublisher',
                'author' => 'Sumari Agus Prasetyo, S.Kom',
                'type' => 'offline',
                'year' => null,
                'stock' => 1,
                'cover' => null,
            ],
            [
                'id' => "092",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 3,
                'title' => 'Farmakognosi',
                'publisher' => 'APMFI',
                'author' => 'apt. Ricke Suhartono, S.Si., MM',
                'type' => 'offline',
                'year' => null,
                'stock' => 1,
                'cover' => null,
            ],
            [
                'id' => "093",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 3,
                'title' => 'Pendidikan Agama Islam dan Biudi Pekerti X',
                'publisher' => 'Yrama Widya',
                'author' => 'Nurlailah',
                'type' => 'offline',
                'year' => null,
                'stock' => 15,
                'cover' => null,
            ],
            [
                'id' => "094",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 3,
                'title' => 'Pendidikan Agama Islam dan Biudi Pekerti XI',
                'publisher' => 'Yrama Widya',
                'author' => 'Nurlailah',
                'type' => 'offline',
                'year' => null,
                'stock' => 14,
                'cover' => null,
            ],
            [
                'id' => "095",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 3,
                'title' => 'Pendidikan Agama Islam dan Biudi Pekerti XII',
                'publisher' => 'Yrama Widya',
                'author' => 'Nurlailah',
                'type' => 'offline',
                'year' => null,
                'stock' => 13,
                'cover' => null,
            ],
            [
                'id' => "096",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 3,
                'title' => 'Pendidikan Kewarganegaraan X',
                'publisher' => 'Yrama Widya',
                'author' => 'Nur Wahyu Rochmadi',
                'type' => 'offline',
                'year' => null,
                'stock' => 18,
                'cover' => null,
            ],
            [
                'id' => "097",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 3,
                'title' => 'Pendidikan Kewarganegaraan X',
                'publisher' => 'Yrama Widya',
                'author' => 'Nur Wahyu Rochmadi',
                'type' => 'offline',
                'year' => null,
                'stock' => 18,
                'cover' => null,
            ],
            [
                'id' => "098",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 3,
                'title' => 'Psikologi Kepribadian',
                'publisher' => 'IRCiSoD',
                'author' => 'Lynn Wilcox',
                'type' => 'offline',
                'year' => null,
                'stock' => 2,
                'cover' => null,
            ],

            [
                'id' => "099",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 3,
                'title' => 'Pendidikan Pncasila X',
                'publisher' => 'Yrama Widya',
                'author' => 'M. Taupan & Ine Ariyani S.',
                'type' => 'offline',
                'year' => null,
                'stock' => 15,
                'cover' => null,
            ],
            [
                'id' => "100",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 3,
                'title' => 'Pendidikan Pncasila XI',
                'publisher' => 'Yrama Widya',
                'author' => 'M. Taupan & Ine Ariyani S.',
                'type' => 'offline',
                'year' => null,
                'stock' => 15,
                'cover' => null,
            ],
            [
                'id' => "101",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 3,
                'title' => 'Pendidikan Pncasila XII',
                'publisher' => 'Yrama Widya',
                'author' => 'M. Taupan & Ine Ariyani S.',
                'type' => 'offline',
                'year' => null,
                'stock' => 15,
                'cover' => null,
            ],
            [
                'id' => "102",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 3,
                'title' => 'AutoCad',
                'publisher' => '-',
                'author' => 'Mikael Sugianto',
                'type' => 'offline',
                'year' => null,
                'stock' => 1,
                'cover' => null,
            ],
            [
                'id' => "901",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 3,
                'title' => 'Antropologi sosial budaya',
                'publisher' => 'Lakeisha',
                'author' => 'Sriyana, M.Sos, M.Si.',
                'type' => 'online',
                'year' => null,
                'stock' => 1,
                'cover' => 'covers/antropologi-sosial-budaya.jpg',
                'file' => 'books/antropologi-sosial-budaya.pdf',
            ],
            [
                'id' => "902",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 3,
                'title' => 'Desain Dan Pemrograman Multimedia ',
                'publisher' => 'Cerdar ulet kreatif',
                'author' => 'Wandah Wibawanto. S.Sn, M.Ds.',
                'type' => 'online',
                'year' => null,
                'stock' => 1,
                'cover' => 'covers/desain-dan-pemrograman-multimedia.jpg',
                'file' => 'books/desain-dan-pemrograman-multimedia.pdf',
            ],
            [
                'id' => "903",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 3,
                'title' => 'Administrasi Sistem Jaringan',
                'publisher' => 'pustaka media guru',
                'author' => 'Nikmah Daulae, S.Pd, MTA.',
                'type' => 'online',
                'year' => null,
                'stock' => 1,
                'cover' => 'covers/admisnistrasi-sistem-jaringan.jpg',
                'file' => 'books/admisnistrasi-sistem-jaringan.pdf',
            ],
            [
                'id' => "904",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 3,
                'title' => 'Etika dan Perilaku Kesehatan',
                'publisher' => 'CV. Absolute Media',
                'author' => 'Dr. Irwan, S.Km, M.Kes',
                'type' => 'online',
                'year' => null,
                'stock' => 1,
                'cover' => 'covers/etika-dan-perilaku-kesehatan.jpg',
                'file' => 'books/etika-dan-perilaku-kesehatan.pdf',
            ],
            [
                'id' => "905",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 3,
                'title' => 'Filsafat dan Ilmu Logika',
                'publisher' => 'Muhammadiyah University press',
                'author' => 'Asc. Prof. Dr. Waston, M.Hum',
                'type' => 'online',
                'year' => null,
                'stock' => 1,
                'cover' => 'covers/filsafat-ilmu-dan-logika.jpg',
                'file' => 'books/filsafat-ilmu-dan-logika.pdf',
            ],
            [
                'id' => "906",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 3,
                'title' => 'Filsafat Logika',
                'publisher' => 'CV. Literasi Nusantara Abadi',
                'author' => 'Dewi Lestari Pardede, S.Pd, M.Pd.',
                'type' => 'online',
                'year' => null,
                'stock' => 1,
                'cover' => 'covers/filsafat-logika.jpg',
                'file' => 'books/filsafat-logika.pdf',
            ],
            [
                'id' => "907",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 3,
                'title' => 'Informatika kesehatan',
                'publisher' => 'CV. Budi Utama',
                'author' => 'Hetty Ismainar, Amd.Keb,SKM., MPH.',
                'type' => 'online',
                'year' => null,
                'stock' => 1,
                'cover' => 'covers/informatika-kesehatan.jpg',
                'file' => 'books/informatika-kesehatan.pdf',
            ],
            [
                'id' => "908",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 3,
                'title' => 'Kajian Tanah dalam Geografi',
                'publisher' => 'Insania',
                'author' => 'Kuswaji Dwi Priyono',
                'type' => 'online',
                'year' => null,
                'stock' => 1,
                'cover' => 'covers/kajian-tanah-dalam-perspektif-geografi.jpg',
                'file' => 'books/kajian-tanah-dalam-perspektif-geografi.pdf',
            ],
            [
                'id' => "909",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 3,
                'title' => 'Keperawatan Krisis',
                'publisher' => 'PT. Global Eksekutif Teknologi',
                'author' => 'Galvani Volta Simanjuntak',
                'type' => 'online',
                'year' => null,
                'stock' => 1,
                'cover' => 'covers/keperawatan-krisis.jpg',
                'file' => 'books/keperawatan-krisis.pdf',
            ],
            [
                'id' => "910",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 3,
                'title' => 'kewirausahaan Theopreneurship',
                'publisher' => 'PT. Rajagrafindo Persada',
                'author' => 'I Nyoman Putra Yasa',
                'type' => 'online',
                'year' => null,
                'stock' => 1,
                'cover' => 'covers/kewirausahaantheopreneurship.jpg',
                'file' => 'books/kewirausahaantheopreneurship.pdf',
            ],
            [
                'id' => "911",
                'isbn' => '978-3-16-148410-0',
                'category_id' => 3,
                'title' => 'Sejarah Hukum Indonesia',
                'publisher' => 'Kencana',
                'author' => 'Prof. Dr. Sutan Remy Sjahdeini, S.H',
                'type' => 'online',
                'year' => null,
                'stock' => 1,
                'cover' => 'covers/sejarah-hukum-indonesia.jpg',
                'file' => 'books/sejarah-hukum-indonesia.pdf',
            ],
        ];

        foreach ($books as $book) {
            \App\Models\Book::create($book);
        }
    }
}
